[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "20"

[build]
  publish = "dist"
  command = "git submodule update --init --recursive && npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run generate && npx pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"